#!/bin/sh

CIL_MACHINE="bool=1,2 short=2,2 int=2,2 long=4,2 long_long=8,2 float=4,2 double=4,2 long_double=4,2 pointer=2,2 enum=2,2 fun=1,2 alignof_string=1 max_alignment=2 size_t=unsigned_int wchar_t=unsigned_int char_signed=true big_endian=false const_string_literals=true __thread_is_keyword=false __builtin_va_list=true underscore_name=true void=1" /home/rshea/git/lis-core/lis/lis --envmachine $*
