COMPONENT=MultihopLogTapRadioCountToLedsAppC

CFLAGS += -I$(TOSDIR)/lib/net/ -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle

PFLAGS += -I$(TOSDIR)/lib/multihoplogtap -I$(TOSDIR)/../apps/RadioCountToLeds

include $(MAKERULES)

