# Author: Roy Shea (royshea@gmail.com)
# Date:  6/1/09

# Ensure the correct enviornment exists
ifndef LIS_PATH
$(error Must set envioronment LIS_PATH to point to the root of your LIS installation.  This is probably something like $$HOME/lis/lis-core)
endif

LIS = $(LIS_PATH)/lis/x86-lis
INCLUDES += -I $(LIS_PATH)/bitlog
LIBS += -L $(LIS_PATH)/bitlog -l bitlog

ifndef $(LISFILE)
LISFILE = default.lis
endif

SOURCES += send_log.c
PREPROCS = $(SOURCES:.c=.i)

.PRECIOUS: %.lis.c

%.i: %.c
	$(CPP) $(INCLUDES) $< -o $@

$(LISGOAL).i: $(PREPROCS)
	cat $^ > $@

$(LISGOAL).c: $(LISGOAL).i
	@echo "Be sure to inculed bitlog.h and link in the bitlog library"
	$(LIS) --lis $(LISFILE) --rlis $(LISFILE).rlis --out tmp.lisi $<
	sed -e '/extern void HOLDER_FUNC(char const   \*msg ) ;/d' < tmp.lisi > tmp.include
	sed -e 's/HOLDER_FUNC("\(.*\) \(.*\)");/bitlog_write_data(\1, \2);/' < tmp.include > tmp.bitlog
	cp tmp.bitlog $@
	rm tmp.bitlog tmp.include tmp.lisi

$(LISGOAL).o: $(LISGOAL).c
	$(CC) -c $(CFLAGS) $(INCLUDES) $< -o $@

lis: $(LISGOAL).o
	$(CC) $(CFLAGS) $? $(LIBS) -o $(LISGOAL)

lis_clean: clean
	rm -f $(LISFILE).rlis $(LISGOAL).o $(LISGOAL).c *.i
